export const Clinic = [
  {
    id: 1,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "Общая Онкология",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Атаджанова Нилюфар Рахимовна",
        vrachImg:
          "https://nssmed.uz/static/media/nilufar.1767647d0320dea47a73.jpg",
        vrachRating: 4,
        vrachJob: "Онкогинеколог",
        staj: "Стаж более 16 лет",
      },
      {
        jobId: 2,
        name: "Ахмедов Одилжон Мухамеджанович",
        vrachImg:
          "https://nssmed.uz/static/media/odil.eb85e2a5948b0e2262fb.jpg",
        vrachRating: 4,
        vrachJob: "Онкохирург и онкогинеколог",
        staj: "Стаж более 26 лет",
      },
      {
        jobId: 3,
        name: "Умарова Нозима Абдувохидовна",
        vrachImg:
          "https://nssmed.uz/static/media/nozima.f47597c946813dc7c063.png",
        vrachRating: 4,
        vrachJob: "Онкогинеколог, к.м.н.",
        staj: "-",
      },
      {
        jobId: 4,
        name: "Бердикулов Жахонгир Икромович",
        vrachImg:
          "https://nssmed.uz/static/media/jaxongir.5245ded494a8c1195482.png",
        vrachRating: 4,
        vrachJob: "онколог",
        staj: "-",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
  {
    id: 2,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "Хирургия",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Аллаяров Улугбек Джураевич",
        vrachImg:
          "https://nssmed.uz/static/media/ulugbek.891ad44bcf484dd1cd50.jpg",
        vrachRating: 4,
        vrachJob: "Xирург",
        staj: "Стаж более 28 лет",
      },
      {
        jobId: 2,
        name: "Сахибоев Дилшод Парпижалилович",
        vrachImg:
          "https://nssmed.uz/static/media/dilshod.fbf84fdbd3c14de4cb3d.png",
        vrachRating: 4,
        vrachJob: "Xирург",
        staj: "Стаж более 16 лет",
      },
      {
        jobId: 3,
        name: "Юсуббоев Ойбек Закирович",
        vrachImg:
          "https://nssmed.uz/static/media/oybek.be860e81b1c6e1927882.jpg",
        vrachRating: 4,
        vrachJob: "сосудистый хирург (флеболог)",
        staj: "Стаж более 22 лет",
      },
      {
        jobId: 4,
        name: "Урмонова Нилуфар Мансуржановна",
        vrachImg:
          "https://nssmed.uz/static/media/proktolog.3866309ce3f45867ffd3.png",
        vrachRating: 4,
        vrachJob: "Проктолог",
        staj: "Стаж более 22 лет",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
  {
    id: 3,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "Гинекология",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Атаджанова Нилюфар Рахимовна",
        vrachImg:
          "https://nssmed.uz/static/media/nilufar.1767647d0320dea47a73.jpg",
        vrachRating: 4,
        vrachJob: "Гинеколог",
        staj: "Стаж более 16 лет",
      },
      {
        jobId: 2,
        name: "Александр Викторович Калягин",
        vrachImg:
          "https://nssmed.uz/static/media/aleksandr.ec12084a999158f5cdbb.png",
        vrachRating: 4,
        vrachJob: "Гинеколог",
        staj: "Стаж более 26 лет",
      },
      {
        jobId: 3,
        name: "Уразбаев Умид Джуманиязович",
        vrachImg:
          "https://nssmed.uz/static/media/umid.2e77c2ecfe6b51945e93.png",
        vrachRating: 4,
        vrachJob: "Акушер-гинеколог",
        staj: "Стаж более 16 лет",
      },
      {
        jobId: 4,
        name: "Атаджанов Мурад Рахимович",
        vrachImg:
          "https://nssmed.uz/static/media/murod.ebf5f595ebdf9b38ea76.png",
        vrachRating: 4,
        vrachJob: "Акушер-гинеколог",
        staj: "Стаж более 10 лет",
      },
      {
        jobId: 5,
        name: "Салиева Умида Хабибуллаевна",
        vrachImg:
          "https://nssmed.uz/static/media/umida.6f23a6bac0b07d15dbf2.png",
        vrachRating: 4,
        vrachJob: "Гинеколог",
        staj: "-",
      },
      {
        jobId: 6,
        name: "Кочиева Альбина Махарбеговна",
        vrachImg:
          "https://nssmed.uz/static/media/albina.4c176ec58259909d64a2.png",
        vrachRating: 4,
        vrachJob: "Акушер-гинеколог",
        staj: "Стаж более 3 лет",
      },
      {
        jobId: 7,
        name: "Исанбаева Ландыш Мухаммедовна",
        vrachImg:
          "https://nssmed.uz/static/media/landish.8f150ef20b50d147ddc6.png",
        vrachRating: 4,
        vrachJob: "Гинеколог",
        staj: "-",
      },
      {
        jobId: 8,
        name: "Рузиева Лазиза Фазлиддиновна",
        vrachImg:
          "https://nssmed.uz/static/media/Laziza.5a5bf55867326c0b9e47.png",
        vrachRating: 4,
        vrachJob: "Акушер-гинеколог",
        staj: "-",
      },
      {
        jobId: 9,
        name: "Джалилова Наргиза Махкамовна",
        vrachImg:
          "https://nssmed.uz/static/media/nargiza.a85b5b6e8c020e2750d2.png",
        vrachRating: 4,
        vrachJob: "Акушер-гинеколог",
        staj: "-",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
  {
    id: 4,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "Пластическая хирургия",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Аьлоханов Лазиз Боходирович",
        vrachImg:
          "https://nssmed.uz/static/media/laziz.c16067107656bdc4ae12.jpg",
        vrachRating: 4,
        vrachJob: "Пластический хирург",
        staj: "Стаж более 17 лет",
      },
      {
        jobId: 2,
        name: "Хамракулов Шохрух Фарухович",
        vrachImg:
          "https://nssmed.uz/static/media/shoxruh.bf3798107a78c13d5f6f.png",
        vrachRating: 4,
        vrachJob: "Пластический хирург",
        staj: "Стаж более 8 лет",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
  {
    id: 5,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "Маммология",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Шамансурова Нодира Саидариповна",
        vrachImg:
          "https://nssmed.uz/static/media/nodira.0817b16c978392ce919a.png",
        vrachRating: 4,
        vrachJob: "Маммолог",
        staj: "Более 16 лет опыта",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
  {
    id: 6,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "Урология",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Бахадирханов Мухаммадзариф Мухаммадкабирович",
        vrachImg:
          "https://nssmed.uz/static/media/zarif.fbe607d3a2ddee35e585.png",
        vrachRating: 4,
        vrachJob: "Уролог",
        staj: "Более 10 лет опыта",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
  {
    id: 7,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "Урология",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Халмухамедов Бобур Тахирович",
        vrachImg:
          "https://nssmed.uz/static/media/bobur.37bf7c357f30ba7033ac.png",
        vrachRating: 4,
        vrachJob: "Кардиолог",
        staj: "Более 11 лет опыта",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
  {
    id: 8,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "Невропатология",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Абдуллаев Бобомурод",
        vrachImg:
          "https://nssmed.uz/static/media/bobomurod.82566fe859e271d0c8a7.jpg",
        vrachRating: 4,
        vrachJob: "Невропатолог",
        staj: "Более 20 лет опыта",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
  {
    id: 9,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "Невропатология",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Обидханов Бахадир Саидалимхан.",
        vrachImg:
          "https://nssmed.uz/static/media/baxodir.313c015b053c93909e8a.png",
        vrachRating: 4,
        vrachJob: "Дерматовенеролог, косметолог",
        staj: "Стаж более 11 лет",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
  {
    id: 10,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "Дерматовенерология",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Давуров Абдужалал Мамасабурович",
        vrachImg:
          "https://nssmed.uz/static/media/abdujalol.6e65187de75f1e93c3e5.png",
        vrachRating: 4,
        vrachJob: "Дерматовенеролог. Миколог Микробиолог",
        staj: "Более 26 лет опыта",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
  {
    id: 11,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "УЗИ",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Камолидинова Фируза Файзуллаевна",
        vrachImg:
          "https://nssmed.uz/static/media/feruza.19d165f2747f2b176197.jpg",
        vrachRating: 4,
        vrachJob: "УЗИ",
        staj: "Более 16 лет опыта",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
  {
    id: 12,
    image: "https://nssmed.uz/static/media/logo.0e9ec22976eb2dd3e13d.png",
    medic: "УЗИ",
    rating: 5,
    ratingText: "19 отзывов",
    clinic: "Частная клиника",
    adres: "Адрес клиники ул. Истирохат, дом 60А, Учтепинский район, Ташкент",
    orientr: "ул. Генерала Узакова",
    phone: "55 508 30 30",
    searchPhone: "Скажите, что нашли номер телефона на Клиникс уз",
    date: "Пн-сб 07:30-20:00",
    job: "Врачи",
    jobs: [
      {
        jobId: 1,
        name: "Довурова Малохат Саибназаровна",
        vrachImg:
          "https://nssmed.uz/static/media/maloxat.5e9a1c6ccd7490440e8a.png",
        vrachRating: 4,
        vrachJob: "Лаборант, заведующий лабораторией",
        staj: "Более 22 лет опыта",
      },
    ],
    consultation: "цена по звонку",
    IUD: "цена по звонку",
    text: "Lab Medical - территория здоровья, где каждый пациент получает индивидуальный комплексный подход и доступ к лучшим мировым медицинским технологиям. Мы собрали уникальную команду экспертов – которые работают вместе на благо пациентов. Командная работа ...",
    lazer: "цена по звонку",
  },
];
